// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/views/layout/AdminLayout.vue')['default']
    App: typeof import('./src/App.vue')['default']
    BreadcrumbHeader: typeof import('./src/components/GobalLayout/BreadcrumbHeader.vue')['default']
    ContactPersonalInformation: typeof import('./src/components/system/contactPersonalInformation.vue')['default']
    DefaultLayout: typeof import('./src/views/layout/DefaultLayout.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Manage: typeof import('./src/views/pages/system/office/TabItems/manage.vue')['default']
    MethodOfPayment: typeof import('./src/components/system/methodOfPayment.vue')['default']
    Office: typeof import('./src/views/pages/system/office/index.vue')['default']
    OfficeInformation: typeof import('./src/components/system/officeInformation.vue')['default']
    OfficeTable: typeof import('./src/views/pages/system/office/TabItems/officeTable.vue')['default']
    PageNotFound: typeof import('./src/components/GobalLayout/PageNotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableActionMenu: typeof import('./src/components/GobalLayout/TableActionMenu.vue')['default']
    TheMenu: typeof import('./src/components/GobalLayout/TheMenu.vue')['default']
    UploadImage: typeof import('./src/components/GobalLayout/UploadImage.vue')['default']
  }
}
