// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Activity: typeof import('./src/views/Pages/Activity/Activity.vue')['default']
    ActivityDetail: typeof import('./src/views/Pages/Activity/TabItem/ActivityDetail.vue')['default']
    ActivityTable: typeof import('./src/views/Pages/Activity/TabItem/ActivityTable.vue')['default']
    AdminLayout: typeof import('./src/views/Layout/AdminLayout.vue')['default']
    App: typeof import('./src/App.vue')['default']
    BreadcrumbHeader: typeof import('./src/components/GobalLayout/BreadcrumbHeader.vue')['default']
    CardActivity: typeof import('./src/components/GobalLayout/CardActivity.vue')['default']
    CardCareer: typeof import('./src/components/GobalLayout/CardCareer.vue')['default']
    CardEvent: typeof import('./src/components/GobalLayout/CardEvent.vue')['default']
    CardFAQ: typeof import('./src/components/GobalLayout/CardFAQ.vue')['default']
    CareerDetail: typeof import('./src/views/Pages/Activity/TabItem/CareerDetail.vue')['default']
    CareerTable: typeof import('./src/views/Pages/Activity/TabItem/CareerTable.vue')['default']
    Company: typeof import('./src/views/Pages/Company/Company.vue')['default']
    CompanyTable: typeof import('./src/views/Pages/Company/TabItem/CompanyTable.vue')['default']
    Dashboard: typeof import('./src/views/Pages/Dashboard/Dashboard.vue')['default']
    DefaultLayout: typeof import('./src/views/Layout/DefaultLayout.vue')['default']
    Event: typeof import('./src/views/Pages/Event/Event.vue')['default']
    EventTable: typeof import('./src/views/Pages/Event/TabItem/EventTable.vue')['default']
    FAQ: typeof import('./src/views/Pages/FAQ/FAQ.vue')['default']
    FAQTable: typeof import('./src/views/Pages/FAQ/TabItem/FAQTable.vue')['default']
    Feedback: typeof import('./src/views/Pages/Feedback/Feedback.vue')['default']
    FeedbackTable: typeof import('./src/views/Pages/Feedback/TabItem/FeedbackTable.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Index: typeof import('./src/views/Pages/Activity/Index.vue')['default']
    LoginForm: typeof import('./src/views/Pages/Register/LoginForm.vue')['default']
    Manage: typeof import('./src/views/Pages/Activity/TabItem/Manage.vue')['default']
    ManageCareer: typeof import('./src/views/Pages/Activity/TabItem/ManageCareer.vue')['default']
    ModalAddPostContent: typeof import('./src/views/Pages/Company/Modal/ModalAddPostContent.vue')['default']
    RegisterForm: typeof import('./src/views/Pages/Register/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableActionMenu: typeof import('./src/components/GobalLayout/TableActionMenu.vue')['default']
    TheMenu: typeof import('./src/components/GobalLayout/TheMenu.vue')['default']
    UploadImage: typeof import('./src/components/GobalLayout/UploadImage.vue')['default']
    ViewEventDetail: typeof import('./src/views/Pages/Event/TabItem/ViewEventDetail.vue')['default']
    ViewFeedbackDetail: typeof import('./src/views/Pages/Feedback/TabItem/ViewFeedbackDetail.vue')['default']
  }
}
